### ISSUE TITLE
InfluxDB 

### ISSUE THREAD

**Issue by jbdesbas** [PnEcrins/GeoSensor#1]
Salut,

Pas encore testé, mais à tout hasard il existe [InfluxDB](https://www.influxdata.com/products/influxdb/) qui est open-source est visiblement plus adapté que pgSQL pour les longues séries temporelles (capteurs, domotiques, etc..), avec apparemment de bien meilleures performances, une gestion plus facile de l'agrégation des anciennes données, une API intégrée.. (cf https://www.influxdata.com/time-series-database/ )
Peut être utilisé  à la place (en complément ?) de pgSQL  ?

**Comment by camillemonchicourt** [comment]
Oui en effet.
Par ailleurs on teste la mise en place d'une passerelle Lorawan et de capteurs météo et on a fait différents tests, en alimentant une BDD InfluxDB et en y branchant un Grafana. Ça fonctionne bien.

On a testé avec une BDD PostgreSQL aussi et ça fonctionne bien aussi.

On aimerait privilégier PG car on aime et connait mieux PG, mais on regarde aussi du côté d'InfluxDB si jamais c'est bien plus performant, notamment pour les gros volumes de données.

**Comment by jbdesbas** [comment]
Dac' merci du retour, vous avez de chouettes projets ! 👍
